# Generated by Django 4.0.5 on 2022-06-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='profession',
        ),
    ]
