# Generated by Django 4.0.5 on 2022-06-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0003_rename_username_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='location',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
