# Generated by Django 4.0.5 on 2022-06-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0004_alter_hood_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='location',
            field=models.TextField(max_length=60, null=True),
        ),
    ]
