# Generated by Django 4.0.5 on 2022-06-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0005_alter_hood_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
